### ISSUE TITLE
README missing one directory?

### ISSUE THREAD

**Issue by anwac** [yfszzx/stable-diffusion-webui-images-browser#2]
If I am not mistaken then 

> git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser <stable-diffusion-webui project path>/extensions

should probably be 

> git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser <stable-diffusion-webui project path>/extensions/stable-diffusion-webui-images-browser

**Comment by yfszzx** [comment]
git clone will create a new directory named stable-diffusion-webui-images-browser

**Comment by yfszzx** [comment]
Thanks
