### ISSUE TITLE
where do the Collected images go?

### ISSUE THREAD

**Issue by MrPwoz** [yfszzx/stable-diffusion-webui-images-browser#29]
Question as the title says; 
I've noticed that if I click on "collect", the selected image disappears from the folder where it was initially saved (e.g. /stable-diffusion-webui/outputs/img2img-images ) but I can't find the new position in my Outputs folder. 
Trying to guess with a "save link as" I've noticed tha it's maybe stored in a temp folder?

Corollary to this question: is there a way to bring back to the initial position the collected image?
If I look in the Favourites tab, where the images are showed after being collected, I only see options to send the img to the main sections (txt2img and others) and to delete it, but nothing related to undoing the "collect" action.

**Comment by yfszzx** [comment]
The selected image should  not  disappear from the folder  in principle.

Default faverites fold  is 'log/images' which is setted at setting interface 'Paths for saving - Directory for saving images using the Save button'
