### ISSUE TITLE
Delete option is missing

### ISSUE THREAD

**Issue by vootox** [yfszzx/stable-diffusion-webui-images-browser#31]
After selecting an image the Delete option disappears. 
<img width="856" alt="Screenshot 2022-11-01 182451" src="https://user-images.githubusercontent.com/27273724/199185715-a493a8c9-788f-4874-911e-7ecc93e75715.png">

**Comment by bl4ckfyr3** [comment]
same here

**Comment by a-l-e-x-d-s-9** [comment]
For me too after a git pull, also all other options, like General Info, and sending to img2img are not available. Only showing and browsing images are working,

**Comment by yfszzx** [comment]
done
