### ISSUE TITLE
Image Info is gone.

### ISSUE THREAD

**Issue by MaximumBlast** [yfszzx/stable-diffusion-webui-images-browser#34]
Hey, all the prompt info for the images i see in the image browser are gone. I am not sure if that has to to with me starting the webUI with the "webui-user.bat" is that the right way to do it? I added that "git pull" line in there. Seems to me it install new stuff everytime i start. It's the only way the WebUI will start for me. Clicking "webui.py" or "launch.py" doesn't do anything.

**Comment by Omegastick** [comment]
+1. I'm also seeing this error in the console:

```Uncaught (in promise) ReferenceError: images_history_turnpage is not defined```

**Comment by MaximumBlast** [comment]
I got help over in the Automatic1111 discussions, check here:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4108

**Comment by MaximumBlast** [comment]
Its a bug with the new extension manager

**Comment by MaximumBlast** [comment]
Did you update both the SD-WebUI from Automatic1111   AND   the Image Browser Extension?

**Comment by topdeckg** [comment]
git status in both the main directory and extensions directory tell me everything is up to date

**Comment by younyokel** [comment]
> The tab doesn't even load now.

You may not have a refreshing tab because you have to click on "Next Page" to refresh it.

**Comment by a-l-e-x-d-s-9** [comment]
I upgraded image browser and stable diffusion, in image browser when selecting a picture, General Info and File Path are showing no information.

**Comment by topdeckg** [comment]
> > The tab doesn't even load now.
> 
> You may not have a refreshing tab because you have to click on "Next Page" to refresh it.

That's inside the tab. It no longer appears in the UI.

**Comment by yfszzx** [comment]
done

**Comment by MaximumBlast** [comment]
> I upgraded image browser and stable diffusion, in image browser when selecting a picture, General Info and File Name are showing no information.

You need to restart Gradio UI for it to work, it is a recent bug that's being worked on. There are 2 ways - you can either go to the Settings tab, at the bottom there is an orange "Restart Gradio~" button. Or you can go to the extensions tab and press "Apply and restart UI".
