### ISSUE TITLE
Extension strips initial / from path name set in webui settings.

### ISSUE THREAD

**Issue by MrAcademy** [yfszzx/stable-diffusion-webui-images-browser#4]
In the webui I have my images directory set to /mnt/whatever/foo and in this extension it becomes mnt/whatever/foo instead, so it will not load any of my images.  Whatever is stripping the initial / is in error.

**Comment by yfszzx** [comment]
the images should put to extensions/stable-diffusion-webui-images-browser](https://github.com/yfszzx/stable-diffusion-webui-images-browser, not under ebui images directory

**Comment by yfszzx** [comment]
fixed

**Comment by MrAcademy** [comment]
Thank you so much - this is a wonderful extension!
