### ISSUE TITLE
[idea] Filter - only show images from x past days

### ISSUE THREAD

**Issue by ophoria** [yfszzx/stable-diffusion-webui-images-browser#41]
Since I usually have >100 000 images  and it rescans them all everytime it takes  a while each time I refresh: Add the feature to set it so it only shows images created the last X days instead, that way people can focus it on their current session/project. I'd be happy to pay you a dinner for the feature, just share paypal. :P

**Comment by yfszzx** [comment]
Just now，I have tried to do this, but found that the directory structure must be cached. This is a big project, but few people may use it. Therefore,I recommend to move the early pictures to other directories.
