### ISSUE TITLE
Favorites misspelled as 'faverites' in notification of adding to collection

### ISSUE THREAD

**Issue by Sutranaut** [yfszzx/stable-diffusion-webui-images-browser#48]
When you click on Collect the notification reads "Added to faverites" instead of "Added to favorites" see attached screenshot 
[screenshot](https://i.imgur.com/rlK7rFz.png)

**Comment by Ju1-js** [comment]
@Sutranaut This was patched at some point, you can probably close this issue now.

**Comment by Sutranaut** [comment]
@Ju1-js Verified and closed, thanks for the update
