### ISSUE TITLE
[Feature Request] Option to not have "Send to img2img" switch checkpoints

### ISSUE THREAD

**Issue by stevenamoreno15** [yfszzx/stable-diffusion-webui-images-browser#65]
![image](https://user-images.githubusercontent.com/81851131/208283199-fc47fcff-140a-4c41-a822-2d7619ea72cd.png)

Pretty much the title.

As it is right now, it automatically switches your checkpoint to the one your sent image uses, which can be pretty inconvenient when you didn't want that and now have to wait for the checkpoint to load and then wait again when you switch it back. This happens for "Send to text2img", "Send to img2img", and "Send to inpaint".

It would be great to have a toggleable option in the settings or in a config file to be able to send image parameters without switching the checkpoint.

**Comment by Ju1-js** [comment]
The send-to buttons are generated by the `modules.generation_parameters_copypaste.create_buttons(["txt2img", "img2img", "inpaint", "extras"])`, so this feature would have to be implemented by the main `stable-diffusion-webui` repo.

**Comment by Ju1-js** [comment]
@cheesesteak45 In fact, this might already be a feature for the webui:
![image](https://user-images.githubusercontent.com/40339350/208289709-af078d53-08ff-4501-b0aa-a4cfc9da88be.png)
(I haven't had the time to test it)

**Comment by stevenamoreno15** [comment]
You would be exactly right. Can't believe I missed this.
Thanks for the reply and sorry for opening an issue over this.
