### ISSUE TITLE
[Feature request]: send image itself together with prompt when clicking Send to img2img

### ISSUE THREAD

**Issue by jnpatrick99** [yfszzx/stable-diffusion-webui-images-browser#7]
Can you make it so the image itself is also sent to the img2img? Sometimes Image Browser is used to outpaint or inpaint existing (old) images.

That will fix several issues and implement requests in the original stable-diffusion-webui repo:https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2892 https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2783  https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2941 

Thanks!

**Comment by yfszzx** [comment]
This function has been added to the new version, but there are still some problems with the new version, which will be submitted later
