### ISSUE TITLE
Cannot read pic info

### ISSUE THREAD

**Issue by QinCaii** [yfszzx/stable-diffusion-webui-images-browser#96]
Cannot read picture info and preview
click the picture will lead to next
![tmp2101](https://user-images.githubusercontent.com/49438338/234757189-388afdd3-5ae4-450c-a025-82fd235aa6e9.png)
imgbrowser: a42c7a3
webui: 22bcc7be

**Comment by daddy32** [comment]
Same here. Cannot choose any actions ("Move to favorities", "Send to img2img" etc) either.

**Comment by daddy32** [comment]
This extension seems abandoned, the solution is supposed to be to install fork linked from wiki:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions#image-browser

**Comment by QinCaii** [comment]
> This extension seems abandoned, the solution is supposed to be to install fork linked from wiki: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions#image-browser

Thank you, this extension works, but there is still a problem.
I cannot preview a picture in full screen as before.
I don't know if this is a problem with webui or gradio, but not img browser
